// ============================================================================
// Maps an emoji character → the directory name Microsoft Fluent UI Emoji uses
// for that emoji in github.com/microsoft/fluentui-emoji.
//
// File structure inside that repo for each entry:
//   assets/<Directory Name>/3D/<directory_name_lowercased_with_underscores>_3d.png
//   assets/<Directory Name>/Color/<…>_color.svg
//
// Example for "🔥":
//   directory: "Fire"
//   3D PNG:    "fire_3d.png"
//   URL path:  /assets/Fire/3D/fire_3d.png
//
// To extend: add the emoji char as the key and the exact directory name
// (case-sensitive, with spaces) as the value. Filename is computed.
// ============================================================================

export const EMOJI_TO_FLUENT_NAME: Record<string, string> = {
  // ---- Vision-themed emojis (used by the vision icon picker) ----
  // Directory names verified against microsoft/fluentui-emoji (all 200).
  // (🦋 🌊 🌌 📈 already exist further down — not re-added here.)
  '👑': 'Crown',
  '💎': 'Gem stone',
  '🦅': 'Eagle',
  '🕊️': 'Dove',
  '⚡': 'High voltage',
  '💯': 'Hundred points',
  '🔑': 'Key',
  '🗝️': 'Old key',
  '🏹': 'Bow and arrow',
  '⚓': 'Anchor',
  // ---- Special / standalone emojis used outside the habit picker ----
  '🔥': 'Fire',
  '✨': 'Sparkles',
  '🎉': 'Party popper',
  '🌱': 'Seedling',
  // Note the LOWERCASE "europe" — that's how the directory is actually named
  // in microsoft/fluentui-emoji. With "Europe-Africa" the CDN returns 403 and
  // every render falls back to emojicdn, adding ~0.5–1s of perceived delay.
  '🌍': 'Globe showing europe-africa',
  '🌲': 'Evergreen tree',
  '🌳': 'Deciduous tree',
  '🌟': 'Glowing star',
  '⭐': 'Star',

  // ---- POSITIVE habit picker emojis ----
  // Fitness & body
  '🏃': 'Person running',
  '🚴': 'Person biking',
  '🏋️': 'Person lifting weights',
  '🧘': 'Person in lotus position',
  '🤸': 'Person cartwheeling',
  '🥊': 'Boxing glove',
  '⚽': 'Soccer ball',
  '🏀': 'Basketball',
  '🏊': 'Person swimming',
  '🚶': 'Person walking',
  '💪': 'Flexed biceps',
  '🧗': 'Person climbing',
  '🏌️': 'Person golfing',
  '🏄': 'Person surfing',
  '🚣': 'Person rowing boat',
  '🤽': 'Person playing water polo',
  '🥋': 'Martial arts uniform',
  '🏐': 'Volleyball',
  '🎾': 'Tennis',
  '🎳': 'Bowling',
  '🛹': 'Skateboard',
  '🛼': 'Roller skate',
  '⛸️': 'Ice skate',
  '🎿': 'Skis',
  '🏂': 'Snowboarder',
  '🤿': 'Diving mask',
  '🥏': 'Flying disc',
  // Healthy food
  '🍎': 'Red apple',
  '🥗': 'Green salad',
  '🥦': 'Broccoli',
  '🥕': 'Carrot',
  '🍓': 'Strawberry',
  '🥑': 'Avocado',
  '🍌': 'Banana',
  '🥚': 'Egg',
  '🍞': 'Bread',
  '🥛': 'Glass of milk',
  '🥬': 'Leafy green',
  '🌽': 'Ear of corn',
  '🥒': 'Cucumber',
  '🫐': 'Blueberries',
  '🍇': 'Grapes',
  '🍊': 'Tangerine',
  '🍋': 'Lemon',
  '🍐': 'Pear',
  '🍒': 'Cherries',
  '🍅': 'Tomato',
  '🐟': 'Fish',
  '🍳': 'Cooking',
  '🥜': 'Peanuts',
  '🌶️': 'Hot pepper',
  '🫑': 'Bell pepper',
  // Healthy drinks
  '💧': 'Droplet',
  '☕': 'Hot beverage',
  '🍵': 'Teacup without handle',
  '🧋': 'Bubble tea',
  '🥤': 'Cup with straw',
  '🧉': 'Mate',
  // Sleep / wellness
  '😴': 'Sleeping face',
  '🛏️': 'Bed',
  '🌙': 'Crescent moon',
  '☀️': 'Sun',
  '🌅': 'Sunrise',
  '🌄': 'Sunrise over mountains',
  '🧠': 'Brain',
  '💭': 'Thought balloon',
  '🕯️': 'Candle',
  '🌿': 'Herb',
  '🛁': 'Bathtub',
  '🚿': 'Shower',
  '🪥': 'Toothbrush',
  '🧼': 'Soap',
  '🧴': 'Lotion bottle',
  '🪒': 'Razor',
  // Health / medical
  '💊': 'Pill',
  '🩺': 'Stethoscope',
  '🦷': 'Tooth',
  '🧬': 'Dna',
  '🫀': 'Anatomical heart',
  '🫁': 'Lungs',
  // Books / learning
  '📚': 'Books',
  '📖': 'Open book',
  '📝': 'Memo',
  '✏️': 'Pencil',
  '🎓': 'Graduation cap',
  '💡': 'Light bulb',
  '📊': 'Bar chart',
  '📰': 'Newspaper',
  '📜': 'Scroll',
  '🖊️': 'Pen',
  '🔖': 'Bookmark',
  '📑': 'Bookmark tabs',
  '📒': 'Ledger',
  // Productivity
  '💼': 'Briefcase',
  '📅': 'Calendar',
  '⏰': 'Alarm clock',
  '⏱️': 'Stopwatch',
  '✅': 'Check mark button',
  '🎯': 'Bullseye',
  '🗒️': 'Spiral notepad',
  '📌': 'Pushpin',
  '📍': 'Round pushpin',
  '📎': 'Paperclip',
  '🗓️': 'Spiral calendar',
  '🧭': 'Compass',
  // Money (saving)
  '💰': 'Money bag',
  '💵': 'Dollar banknote',
  '🪙': 'Coin',
  '💴': 'Yen banknote',
  '💶': 'Euro banknote',
  '💷': 'Pound banknote',
  '🏦': 'Bank',
  '📈': 'Chart increasing',
  '💱': 'Currency exchange',
  // Music & creative
  '🎵': 'Musical note',
  '🎶': 'Musical notes',
  '🎸': 'Guitar',
  '🎹': 'Musical keyboard',
  '🎨': 'Artist palette',
  '📷': 'Camera',
  '🎬': 'Clapper board',
  '🎥': 'Movie camera',
  '📹': 'Video camera',
  '🎤': 'Microphone',
  '🎧': 'Headphone',
  '🎻': 'Violin',
  '🥁': 'Drum',
  '🎺': 'Trumpet',
  '🎷': 'Saxophone',
  '🖌️': 'Paintbrush',
  '🖼️': 'Framed picture',
  '🧵': 'Thread',
  '🧶': 'Yarn',
  '✂️': 'Scissors',
  '📐': 'Triangular ruler',
  '📏': 'Straight ruler',
  '🛠️': 'Hammer and wrench',
  '🔧': 'Wrench',
  '🔨': 'Hammer',
  '⚙️': 'Gear',
  '⛏️': 'Pick',
  '🪛': 'Screwdriver',
  // Tech / work
  '🖥️': 'Desktop computer',
  '🖱️': 'Computer mouse',
  '💾': 'Floppy disk',
  '📡': 'Satellite antenna',
  // Travel / movement
  '✈️': 'Airplane',
  '🚆': 'Train',
  '🚇': 'Metro',
  '🚗': 'Automobile',
  '🚙': 'Sport utility vehicle',
  '🚌': 'Bus',
  '🛴': 'Kick scooter',
  '⛵': 'Sailboat',
  '🛶': 'Canoe',
  '🚢': 'Ship',
  '🗺️': 'World map',
  '🧳': 'Luggage',
  // Family / care
  '👶': 'Baby',
  '👨‍👩‍👧': 'Family man woman girl',
  '🤱': 'Breast-feeding',
  '👨‍👩‍👦': 'Family man woman boy',
  // Communication
  '🗣️': 'Speaking head',
  '💬': 'Speech balloon',
  '📣': 'Megaphone',
  '🔔': 'Bell',
  '✉️': 'Envelope',
  '📧': 'E-mail',
  '🤝': 'Handshake',
  '🤗': 'Smiling face with open hands',
  // Achievement
  '🏆': 'Trophy',
  '🥇': '1st place medal',
  '🥈': '2nd place medal',
  '🥉': '3rd place medal',
  '🏅': 'Sports medal',
  '🎖️': 'Military medal',
  '🚀': 'Rocket',
  '🌈': 'Rainbow',
  '🎁': 'Wrapped gift',
  '🎀': 'Ribbon',
  '🏁': 'Chequered flag',
  '🚩': 'Triangular flag',
  '🎗️': 'Reminder ribbon',
  // Spiritual / mindset
  '❤️': 'Red heart',
  '🙏': 'Folded hands',
  '💖': 'Sparkling heart',
  '🌸': 'Cherry blossom',
  '🦋': 'Butterfly',
  '🕉️': 'Om',
  '☮️': 'Peace symbol',
  '☯️': 'Yin yang',
  '✡️': 'Star of david',
  '☪️': 'Star and crescent',
  '☸️': 'Wheel of dharma',
  '🛐': 'Place of worship',
  '⛪': 'Church',
  '🕍': 'Synagogue',
  '🕌': 'Mosque',
  '🛕': 'Hindu temple',
  // Eyes / awareness
  '👁️': 'Eye',
  '👀': 'Eyes',
  // Nature
  '🌻': 'Sunflower',
  '🌷': 'Tulip',
  '🌹': 'Rose',
  '🌺': 'Hibiscus',
  '🌼': 'Blossom',
  '🪷': 'Lotus',
  '🌾': 'Sheaf of rice',
  '🌵': 'Cactus',
  '🌴': 'Palm tree',
  '🪴': 'Potted plant',
  '🍀': 'Four leaf clover',
  '🍃': 'Leaf fluttering in wind',
  '🍂': 'Fallen leaf',
  '🍁': 'Maple leaf',
  '🌊': 'Water wave',
  '🏔️': 'Snow-capped mountain',
  '⛰️': 'Mountain',
  '🏝️': 'Desert island',
  '🏖️': 'Beach with umbrella',
  // Weather
  '☁️': 'Cloud',
  '⛅': 'Sun behind cloud',
  '🌧️': 'Cloud with rain',
  '⛄': 'Snowman without snow',
  '❄️': 'Snowflake',
  '🌪️': 'Tornado',
  // Stars / space
  '💫': 'Dizzy',
  '☄️': 'Comet',
  '🌠': 'Shooting star',
  '🌌': 'Milky way',
  '🪐': 'Ringed planet',
  // Animals
  '🐦': 'Bird',
  '🐶': 'Dog face',
  '🐱': 'Cat face',
  '🐰': 'Rabbit face',
  '🦊': 'Fox',
  '🐻': 'Bear',
  '🐨': 'Koala',
  '🐼': 'Panda',
  '🐯': 'Tiger face',
  '🦁': 'Lion',
  '🐢': 'Turtle',
  '🦉': 'Owl',
  '🐝': 'Honeybee',
  '🐬': 'Dolphin',
  '🐳': 'Spouting whale',
  // Positive emotions
  '🤩': 'Star-struck',
  '😊': 'Smiling face with smiling eyes',
  '😃': 'Grinning face with big eyes',
  '😄': 'Grinning face with smiling eyes',
  '😁': 'Beaming face with smiling eyes',
  '🥰': 'Smiling face with hearts',
  '😎': 'Smiling face with sunglasses',
  '🤔': 'Thinking face',
  '😌': 'Relieved face',
  '🥳': 'Partying face',

  // ---- NEGATIVE habit picker emojis ----
  // Substances
  '🚬': 'Cigarette',
  '🍺': 'Beer mug',
  '🍷': 'Wine glass',
  '🍸': 'Cocktail glass',
  '🥃': 'Tumbler glass',
  '🥂': 'Clinking glasses',
  '🍾': 'Bottle with popping cork',
  '💉': 'Syringe',
  '🧪': 'Test tube',
  // Junk food
  '🍕': 'Pizza',
  '🍔': 'Hamburger',
  '🍟': 'French fries',
  '🌭': 'Hot dog',
  '🍿': 'Popcorn',
  '🍩': 'Doughnut',
  '🍰': 'Shortcake',
  '🍫': 'Chocolate bar',
  '🍭': 'Lollipop',
  '🍪': 'Cookie',
  '🍦': 'Soft ice cream',
  '🍨': 'Ice cream',
  '🧁': 'Cupcake',
  '🥓': 'Bacon',
  // Screens / games
  '📱': 'Mobile phone',
  '📺': 'Television',
  '🎮': 'Video game',
  '💻': 'Laptop',
  '⌨️': 'Keyboard',
  '📞': 'Telephone receiver',
  // Money waste
  '💸': 'Money with wings',
  '🛍️': 'Shopping bags',
  '💳': 'Credit card',
  '📉': 'Chart decreasing',
  // Gambling
  '🎰': 'Slot machine',
  '🎲': 'Game die',
  '🃏': 'Joker',
  // Lazy / oversleeping
  '🛋️': 'Couch and lamp',
  '🥱': 'Yawning face',
  '😪': 'Sleepy face',
  '⏳': 'Hourglass not done',
  '⌛': 'Hourglass done',
  // Negative emotions
  '😡': 'Pouting face',
  '🤬': 'Face with symbols on mouth',
  '😤': 'Face with steam from nose',
  '🤥': 'Lying face',
  '😈': 'Smiling face with horns',
  '👿': 'Angry face with horns',
  '🙄': 'Face with rolling eyes',
  '😒': 'Unamused face',
  '😞': 'Disappointed face',
  '😟': 'Worried face',
  '😣': 'Persevering face',
  '😭': 'Loudly crying face',
  '😢': 'Crying face',
  '💔': 'Broken heart',
  // Generic warnings
  '⛔': 'No entry',
  '🚫': 'Prohibited',
  '❌': 'Cross mark',
  '⚠️': 'Warning',
  '💀': 'Skull',
  '☠️': 'Skull and crossbones',
  '🔞': 'No one under eighteen',
  '🚭': 'No smoking',
  '🚯': 'No littering',
};

/**
 * Build the jsDelivr URL for an emoji's Microsoft Fluent 3D PNG.
 * Returns null if the emoji isn't in our map (caller should fall back to
 * a different CDN or to the OS glyph).
 */
export function fluent3dUrlFor(emoji: string): string | null {
  // Try the emoji as-is; some emojis include the U+FE0F variation selector
  // which our keys above don't (e.g., '❤️' is stored as '❤' + FE0F).
  // We match both forms to be safe.
  const name =
    EMOJI_TO_FLUENT_NAME[emoji] ??
    EMOJI_TO_FLUENT_NAME[emoji.replace(/️/g, '')];
  if (!name) return null;

  // Directory name preserves spaces/case for the URL path; the filename is
  // lowercased, spaces → underscores.
  const dir = encodeURIComponent(name);
  const filename = encodeURIComponent(name.toLowerCase().replace(/\s+/g, '_'));
  return `https://cdn.jsdelivr.net/gh/microsoft/fluentui-emoji@main/assets/${dir}/3D/${filename}_3d.png`;
}
